import os
from dotenv import load_dotenv

load_dotenv()

DEFAULT_TOKEN_SENT = os.environ.get("DEFAULT_TOKEN_SENT", 10)
DEFAULT_TOKEN_RECEIVED = os.environ.get("DEFAULT_TOKEN_RECEIVED", 0)
DEFAULT_FOLLOWED_BY_ON_LENS = os.environ.get("DEFAULT_FOLLOWED_BY_ON_LENS", 5)
DEFAULT_FOLLOWING_ON_LENS = os.environ.get("DEFAULT_FOLLOWING_ON_LENS", 7)
DEFAULT_FOLLOWED_BY_ON_FARCASTER = os.environ.get(
    "DEFAULT_FOLLOWED_BY_ON_FARCASTER", 5)
DEFAULT_FOLLOWING_ON_FARCASTER = os.environ.get(
    "DEFAULT_FOLLOWING_ON_FARCASTER", 5)
DEFAULT_COMMON_POAPS = os.environ.get("DEFAULT_COMMON_POAPS", 7)
DEFAULT_COMMON_ETH_NFTS = os.environ.get("DEFAULT_COMMON_ETH_NFTS", 5)
DEFAULT_COMMON_POL_NFTS = os.environ.get("DEFAULT_COMMON_POL_NFTS", 5)

default_score_map = {
    'tokenSent': DEFAULT_TOKEN_SENT,
    'tokenReceived': DEFAULT_TOKEN_RECEIVED,
    'followedByOnLens': DEFAULT_FOLLOWED_BY_ON_LENS,
    'followingOnLens': DEFAULT_FOLLOWING_ON_LENS,
    'followedByOnFarcaster': DEFAULT_FOLLOWED_BY_ON_FARCASTER,
    'followingOnFarcaster': DEFAULT_FOLLOWING_ON_FARCASTER,
    'commonPoaps': DEFAULT_COMMON_POAPS,
    'commonEthNfts': DEFAULT_COMMON_ETH_NFTS,
    'commonPolygonNfts': DEFAULT_COMMON_POL_NFTS,
}
